# Generated by Django 5.1.3 on 2024-11-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=50)),
                ('comentario', models.TextField()),
                ('torneo', models.CharField(max_length=50)),
            ],
        ),
    ]
